---
# maintains ports, bianry or repo urls

org: encapsulate
domain_regex: ^([a-zA-Z0-9-]+\.)+[a-zA-Z]{2,}$
monitor_server_dns: monitor.encapsulate.xyz
ansible_port: 8192

architecture_map:
  x86_64: amd64
  aarch64: arm64

default_node_types:
  - validator
  - default

tmp_dir: /tmp

go:
  root: /usr/local/go
  path: "{{ tmp_dir }}/go"
  module111: "on"

genlayer:
  source_url: https://storage.googleapis.com/gh-af/genlayer-node/bin
  validator:
    ports:
      admin_port: 9155
      rpc_port: 9151
      metrics_port: 9153
  webdriver:
    source_url: yeagerai/genlayer-genvm-webdriver
    ports:
      listen_port: 4444
  llm:
    ports:
      listen_port: 3031
  web:
    ports:
      listen_port: 3032
