$ANSIBLE_VAULT;1.1;AES256
38613436393366393833666431633164396136333066333738366536653237306535373335353761
3961653663366638376131633664366238343962333833390a363632646131373164633232393533
34323866306665663065383738313762326536323262343131653832663366623166353230303435
3731346665353939630a393161306262343561633561633831643632666136333137393031666535
65646563373430353263343565623833626165636232636637363966633537386666316665363734
66663436663863363632393863346539363864643738383262386331666238373465353462323735
33653037663734353366323435363934626261623039313431666532363136326336343964373931
35393330616132346463393839333162626136363932653438623735613635653166346438383263
36646536663132303363303632313237363133363336363132343065346464666133323263363462
61353136393032633363613763393732303934623137656336336162326231646661303563613565
64393335386363386537393664356133633536343437666431316363336363326634343264323439
30353934653732626632613762333263396632363337363865353638373739353739633335656235
66653536303638353061313564663662316434646561316336393630626465616434393639363661
34356166376137623236663038343939656135313238303763346466623061313734663338333430
64626538646231666466353439383231396439326336323366616539666361623334386539643538
30356232656664353734383239326538666431383235636161616265343561326230666530363564
31383834343837623836623634636263366366613036626131376639383439656633
