$ANSIBLE_VAULT;1.1;AES256
38313266376463396535393636316663316232306565666634616639653230663963663463653930
6665646437363064336665636630376637353332343166340a643638376231623764306466353865
35333431653130643432666265323330303530326433313439643133626237313138346534663837
3839326637343961390a663237313365653733656363636138366137636232303366633534363737
34313239383062393538653262353136393064356334386335303431383336343561663766643938
66346137376464393431616436336163343161653033663335393230323963373639336261383261
30346234303932643831313264616333663431333537643932653236663930346330633733623131
32326665316339313662633661373730653539363732633437656161353236356431646561663837
34313632666132306331663364363234323664653636356230636231616631626130656465633939
39303263616465373230306131363930373863386134316237646333373433356465326436336236
38323566656639646364643837333934383164643336363566373634636436306431663736333766
34363730313838383164396538646634393566393431343937633765623036316662623262306635
31366438343865393063313665353131656363343635396132326432383735643838366264306237
33386334636461396535313263303463303739383865616532303139633436373432336339366563
61373933666434373565653531623232373464363366373332333031373764613839346231353166
62343165623835353833626266386162323732353661303162663630323934363062396331643266
31656639386332356336396465623238653361633562333537383836633664346237
