---
# maintains directories and paths
llm_home_dir: /opt/{{ service_identifier }}

llm_bin_dir: "{{ llm_home_dir }}/bin"
llm_config_dir: "{{ llm_home_dir }}/config"
llm_env_dir: "{{ llm_home_dir }}/environment"
llm_log_dir: "{{ llm_home_dir }}/log"

llm_directories:
  - "{{ llm_home_dir }}"
  - "{{ llm_bin_dir }}"
  - "{{ llm_config_dir }}"
  - "{{ llm_env_dir }}"
  - "{{ llm_log_dir }}"

llm_log_file_path: "{{ llm_log_dir }}/{{ service_identifier }}.log"

llm_config_file_path: "{{ llm_config_dir }}/{{ llm_config_file_name }}"
llm_lua_script_file_path: "{{ llm_config_dir }}/{{ llm_lua_script_file_name }}"

llm_environment_general_file_path: "{{ llm_env_dir }}/{{ llm_environment_general_file_name }}"
