---
# maintains directories and paths
node_home_dir: /opt/{{ service_identifier }}

node_bin_dir: "{{ node_home_dir }}/bin"
node_config_dir: "{{ node_home_dir }}/config"
node_data_dir: "{{ node_home_dir }}/data"
node_log_dir: "{{ node_home_dir }}/log"
node_key_dir: "{{ node_home_dir }}/key"
node_env_dir: "{{ node_home_dir }}/environment"

node_merkle_dir: "{{ node_data_dir }}/merkle"
node_merkle_forest_dir: "{{ node_merkle_dir }}/forest"
node_merkle_tree_dir: "{{ node_merkle_dir }}/tree"

node_directories:
  - "{{ node_home_dir }}"
  - "{{ node_bin_dir }}"
  - "{{ node_config_dir }}"
  - "{{ node_data_dir }}"
  - "{{ node_env_dir }}"
  - "{{ node_key_dir }}"
  - "{{ node_log_dir }}"
  - "{{ node_merkle_dir }}"
  - "{{ node_merkle_forest_dir }}"
  - "{{ node_merkle_tree_dir }}"

node_config_file_path: "{{ node_config_dir }}/{{ node_config_file_name }}"
node_wallet_file_path: "{{ node_key_dir }}/{{ node_wallet_file_name }}"

node_log_file_path: "{{ node_log_dir }}/{{ service_identifier }}.log"

node_environment_secret_file_path: "{{ node_env_dir }}/{{ node_environment_secret_file_name }}"

node_key_json_file_path: "{{ node_key_dir }}/{{ node_key_json_file_name }}"
