---
- name: Create a temporary directory
  ansible.builtin.file:
    path: "{{ tmp_dir }}/{{ service_identifier }}"
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Download and unarchive
  vars:
    archive_name: "genlayer-node-linux-amd64-{{ genlayer.version }}.tar.gz"
    prefix_url: "{{ system_architecture }}/{{ genlayer.version }}/{{ archive_name }}"
  ansible.builtin.unarchive:
    src: "{{ genlayer.source_url }}/{{ prefix_url }}"
    dest: "{{ tmp_dir }}/{{ service_identifier }}"
    remote_src: true
    owner: root
    group: root
    mode: "0755"

- name: Copy the binary file
  vars:
    binary_subpath: "genlayer-node-linux-amd64/bin"
  ansible.builtin.copy:
    src: "{{ tmp_dir }}/{{ service_identifier }}/{{ binary_subpath }}/{{ node_service_default_binary_name }}"
    dest: "{{ node_bin_dir }}/{{ service_identifier }}"
    remote_src: true
    owner: root
    group: root
    force: true
    mode: "0755"
  notify:
    - Restart service

- name: Clean up the temporary files in /tmp
  ansible.builtin.file:
    path: "{{ tmp_dir }}/{{ service_identifier }}"
    state: absent
