---
- name: Include the ufw vars file
  ansible.builtin.include_vars:
    file: vars/ufw_rules.yml

- name: Apply UFW rules
  ansible.builtin.include_tasks: tasks/apply_ufw_rules.yml
  loop: "{{ node_ufw_rules }}"

- name: Include user creation task
  ansible.builtin.include_tasks: tasks/create_user_and_directories.yml
  vars:
    home: "{{ node_home_dir }}"
    directories: "{{ node_directories }}"
    log_file_path: "{{ node_log_file_path }}"

- name: Include extract binaries task
  ansible.builtin.include_tasks: extract_binaries.yml

- name: Copy node configuration file
  ansible.builtin.template:
    src: "{{ env }}/config.yaml.j2"
    dest: "{{ node_config_file_path }}"
    owner: "{{ service_identifier }}"
    group: "{{ service_identifier }}"
    mode: "0644"
  notify:
    - Restart service

- name: Copy wallet configuration file
  ansible.builtin.template:
    src: "{{ env }}/wallet.yaml.j2"
    dest: "{{ node_wallet_file_path }}"
    owner: "{{ service_identifier }}"
    group: "{{ service_identifier }}"
    mode: "0644"
  notify:
    - Restart service

- name: Fetch secrets from HCP Vault and save to files
  when:
    - type == 'validator'
    - fetch_validator_keys | default(false) | bool
  block:
    - name: Fetch json key and save
      ansible.builtin.include_tasks: tasks/get_and_save_vault_secret.yml
      vars:
        vault_secret_source_path: "{{ project }}/{{ org }}/{{ type }}/{{ node_key_json_file_name }}"
        secret_destination_path: "{{ node_key_json_file_path }}"
        secret_type: json

    - name: Fetch secret environment file
      ansible.builtin.include_tasks: tasks/get_and_save_vault_secret.yml
      vars:
        vault_secret_source_path: "{{ project }}/{{ org }}/{{ type }}/{{ node_environment_secret_file_name }}"
        secret_destination_path: "{{ node_environment_secret_file_path }}"
        secret_type: environment

- name: Copy systemd service file
  ansible.builtin.template:
    src: "{{ env }}/systemd.service.j2"
    dest: /etc/systemd/system/{{ service_identifier }}.service
    owner: root
    group: root
    mode: "0644"
  notify:
    - Reload service
    - Restart service
